### PR TITLE
Build 3.5 of firmware loading driver for 32/64 Windows 10

### PR DESCRIPTION
**Pull request by mattgonzalez**
Scripts to build firmware loading driver cab files for submission to Microsoft
Fixed firmware loading driver release build
Added GlobalSign cross-certificate for driver signing
Added signing tools binaries
Fixed driver version resource
New INX file to generate cross-platform INF files for firmware loading driver
Added installation instructions

### CODE REVIEW

**Comment by ATMakersBill** [comment]
Matt I’m happy to merge this, but would rather make you a manager of this repo. Are you ok with that?

**Comment by mattgonzalez** [comment]
Sorry, I think I pushed that to the wrong repository.  I meant to do a 
pull request.

Sure, go ahead and add me.

**Comment by mattgonzalez** [comment]
Oh, I see - you're referring to an older commit.  I thought you were 
somehow alluding to what I checked in today.

**Comment by ATMakersBill** [comment]
I just think you should have commit privs on this repo

**Pull request merged**
